# Generated by Django 4.2.8 on 2024-03-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerclub', '0004_administrator_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visitor',
            field=models.CharField(choices=[('Yes', 'Да'), ('No', 'Нет')], default=1, max_length=20, verbose_name='Частый гость'),
            preserve_default=False,
        ),
    ]
