# Generated by Django 4.2.8 on 2024-03-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computerclub', '0007_order_field_name_order_update_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='update_at',
        ),
    ]
